changelog:
  categories:
    - title: New Features 🎉
      labels:
        - "enhancement"
    - title: Bug Fix 💊
      labels:
        - "bug"
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: Other Changes 🛠
      labels:
        - "*"
